import List from "components/List";

const items = {
  "M-8FvC3GD8c": {
    title: "Office Break Yoga",
    type: "video",
    duration: 860,
    thumbnail: { src: "https://i.ytimg.com/vi/M-8FvC3GD8c/hqdefault.jpg", height: 360, width: 480 },
    day: [5],
    src: "//www.youtube-nocookie.com/embed/M-8FvC3GD8c",
    pk: "M-8FvC3GD8c",
  },
  "W-9L0J_9qag": {
    title: "Abs Workout",
    type: "video",
    duration: 495,
    thumbnail: { src: "https://i.ytimg.com/vi/W-9L0J_9qag/hqdefault.jpg", height: 360, width: 480 },
    day: [0, 2, 4],
    src: "//www.youtube-nocookie.com/embed/W-9L0J_9qag",
    pk: "W-9L0J_9qag",
  },
  JUP_YdYyfQw: {
    title: "Yoga For Text Neck",
    type: "video",
    duration: 1726,
    thumbnail: { src: "https://i.ytimg.com/vi/JUP_YdYyfQw/hqdefault.jpg", height: 360, width: 480 },
    day: [1, 3],
    src: "//www.youtube-nocookie.com/embed/JUP_YdYyfQw",
    pk: "JUP_YdYyfQw",
  },
  r7xsYgTeM2Q: {
    title: "Sunrise Yoga",
    type: "video",
    duration: 0,
    thumbnail: { src: "https://i.ytimg.com/vi/r7xsYgTeM2Q/hqdefault.jpg", height: 360, width: 480 },
    day: [],
    src: "//www.youtube-nocookie.com/embed/r7xsYgTeM2Q",
    pk: "r7xsYgTeM2Q",
  },
  "7agiIk9KgyI": {
    title: "Yoga For Upper Body Strength",
    type: "video",
    duration: 0,
    thumbnail: { src: "https://i.ytimg.com/vi/7agiIk9KgyI/hqdefault.jpg", height: 360, width: 480 },
    day: [],
    src: "//www.youtube-nocookie.com/embed/7agiIk9KgyI",
    pk: "7agiIk9KgyI",
  },
  plL13JF5BHA: {
    title: "Yoga For Runners",
    type: "video",
    duration: 0,
    thumbnail: { src: "https://i.ytimg.com/vi/plL13JF5BHA/hqdefault.jpg", height: 360, width: 480 },
    day: [],
    src: "//www.youtube-nocookie.com/embed/plL13JF5BHA",
    pk: "plL13JF5BHA",
  },
  nQFf38xeBww: {
    title: "Take 5 Yoga Break!",
    type: "video",
    duration: 364,
    thumbnail: { src: "https://i.ytimg.com/vi/nQFf38xeBww/hqdefault.jpg", height: 360, width: 480 },
    day: [],
    src: "//www.youtube-nocookie.com/embed/nQFf38xeBww",
    pk: "nQFf38xeBww",
  },
  BiWDsfZ3zbo: {
    title: "Wind Down Yoga",
    type: "video",
    duration: 0,
    thumbnail: { src: "https://i.ytimg.com/vi/BiWDsfZ3zbo/hqdefault.jpg", height: 360, width: 480 },
    day: [],
    src: "//www.youtube-nocookie.com/embed/BiWDsfZ3zbo",
    pk: "BiWDsfZ3zbo",
  },
  UEEsdXn8oG8: {
    title: "Wake Up Yoga",
    type: "video",
    duration: 0,
    thumbnail: { src: "https://i.ytimg.com/vi/UEEsdXn8oG8/hqdefault.jpg", height: 360, width: 480 },
    day: [],
    src: "//www.youtube-nocookie.com/embed/UEEsdXn8oG8",
    pk: "UEEsdXn8oG8",
  },
  "X3-gKPNyrTA": {
    title: "Yoga For Neck, Shoulders, Upper Back",
    type: "video",
    duration: 0,
    thumbnail: { src: "https://i.ytimg.com/vi/X3-gKPNyrTA/hqdefault.jpg", height: 360, width: 480 },
    day: [],
    src: "//www.youtube-nocookie.com/embed/X3-gKPNyrTA",
    pk: "X3-gKPNyrTA",
  },
  SedzswEwpPw: {
    title: "Yoga for Neck and Shoulder Relief",
    type: "video",
    duration: 0,
    thumbnail: { src: "https://i.ytimg.com/vi/SedzswEwpPw/hqdefault.jpg", height: 360, width: 480 },
    day: [],
    src: "//www.youtube-nocookie.com/embed/SedzswEwpPw",
    pk: "SedzswEwpPw",
  },
};

export default function Ben() {
  return <List data={items} canEdit={false} />;
}
