name: Weekly Supabase API Call

on:
  schedule:
    # Run every Monday at 00:00 UTC
    - cron: "0 0 * * 1"
  workflow_dispatch: # Allows manual triggering

jobs:
  call-supabase-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase API
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          #!/bin/bash
          set -e
          curl --fail -G '${SUPABASE_URL}/rest/v1/entry' -d "limit-1" -H "apiKey: ${SUPABASE_ANON_KEY} -H "Authorization: Bearer ${SUPABASE_ANON_KEY}"
