name: Weekly Supabase API Call

on:
  schedule:
    # Run every Monday at 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  call-supabase-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase API
        shell: bash
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          curl --fail -G "${SUPABASE_URL}/rest/v1/entry" -d "limit=1" -H "apiKey: ${SUPABASE_ANON_KEY}" -H "Authorization: Bearer ${SUPABASE_ANON_KEY}"
